name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 AM
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.STATS_TOKEN }}
      
      - name: Download stats artifacts
        uses: actions/download-artifact@v3
        with:
          name: github-stats
          path: ./
      
      - name: Update README
        run: |
          node scripts/generate-stats-readme.js
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md stats.svg top-langs.svg
          git diff --staged --quiet || git commit -m "Update GitHub stats"
