name: Update Stats
on:
  schedule:
    - cron: '0 * * * *' # Update daily
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate Stats
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/m3dkata/stats" \
            > stats.json
      - name: Update README
        run: |
          # Update README dynamically here using the fetched stats
